import { useEffect } from 'react'

const SummaryModal = ({ summary, conversationName, onClose }) => {
  useEffect(() => {
    const handleKeyDown = event => {
      if (event.key === 'Escape') {
        onClose()
      }
    }

    document.addEventListener('keydown', handleKeyDown)

    return () => {
      document.removeEventListener('keydown', handleKeyDown)
    }
  }, [onClose])

  return (
    <div
      className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/35 p-0 backdrop-blur-[1px] sm:items-center sm:p-4"
      onMouseDown={event => {
        if (event.target === event.currentTarget) {
          onClose()
        }
      }}
    >
      <section
        role="dialog"
        aria-modal="true"
        aria-labelledby="conversation-summary-title"
        className="flex max-h-[85dvh] w-full flex-col overflow-hidden rounded-t-2xl bg-white shadow-2xl sm:max-w-lg sm:rounded-2xl"
      >
        <div className="flex shrink-0 items-start gap-3 border-b border-slate-200 px-4 py-4 sm:px-5">
          <span
            aria-hidden="true"
            className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-blue-600"
          >
            <svg
              className="size-5"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth="1.8"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="m12 3 .8 2.2A5.8 5.8 0 0 0 16.3 8.7l2.2.8-2.2.8a5.8 5.8 0 0 0-3.5 3.5L12 16l-.8-2.2a5.8 5.8 0 0 0-3.5-3.5l-2.2-.8 2.2-.8a5.8 5.8 0 0 0 3.5-3.5L12 3Zm6.5 12 .4 1.1a2.9 2.9 0 0 0 1.8 1.8l1.1.4-1.1.4a2.9 2.9 0 0 0-1.8 1.8l-.4 1.1-.4-1.1a2.9 2.9 0 0 0-1.8-1.8l-1.1-.4 1.1-.4a2.9 2.9 0 0 0 1.8-1.8l.4-1.1Z"
              />
            </svg>
          </span>

          <div className="min-w-0 flex-1">
            <h2
              id="conversation-summary-title"
              className="text-base font-semibold text-slate-900"
            >
              Conversation recap
            </h2>
            <p className="mt-0.5 truncate text-xs text-slate-500">
              {conversationName
                ? `Latest messages with ${conversationName}`
                : 'A summary of the latest messages'}
            </p>
          </div>

          <button
            type="button"
            onClick={onClose}
            className="flex size-9 shrink-0 items-center justify-center rounded-lg text-slate-400 hover:bg-slate-100 hover:text-slate-700 focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500"
            aria-label="Close conversation recap"
          >
            <svg
              aria-hidden="true"
              className="size-5"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth="2"
            >
              <path strokeLinecap="round" d="m6 6 12 12M18 6 6 18" />
            </svg>
          </button>
        </div>

        <div className="chat-scrollbar min-h-0 overflow-y-auto px-4 py-5 sm:px-5">
          <p className="whitespace-pre-wrap text-sm leading-7 text-slate-700">
            {summary}
          </p>
        </div>

        <div className="flex shrink-0 items-center justify-between gap-3 border-t border-slate-200 bg-slate-50 px-4 py-3 sm:px-5">
          <p className="text-xs text-slate-400">
            Generated by Gemini · Latest 50 messages
          </p>
          <button
            type="button"
            onClick={onClose}
            className="shrink-0 rounded-lg bg-slate-900 px-3.5 py-2 text-xs font-medium text-white transition hover:bg-slate-700 focus:outline-none focus-visible:ring-2 focus-visible:ring-slate-500 focus-visible:ring-offset-2"
          >
            Done
          </button>
        </div>
      </section>
    </div>
  )
}

export default SummaryModal
